theme: jekyll-theme-cayman
title: Modi and the Data
description: A justaposition of snippets from PM Modi's campaign speech in Delhi, September 2013 with data collected on the Indian electorate by ADR and Daksh in 2014. 
